# Generated by Django 2.1.3 on 2018-11-14 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_unit', models.CharField(max_length=10)),
                ('bathrooms', models.CharField(max_length=5)),
                ('bedrooms', models.CharField(max_length=5)),
                ('home_type', models.CharField(max_length=40)),
                ('last_sold_date', models.DateField(null=True)),
                ('last_sold_price', models.IntegerField(null=True)),
                ('price', models.CharField(max_length=10)),
                ('property_size', models.IntegerField(null=True)),
                ('tax_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_year', models.IntegerField(null=True)),
                ('year_built', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAddress',
            fields=[
                ('property_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=75)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RentalDetails',
            fields=[
                ('rental_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rentzestimate_amount', models.IntegerField(null=True)),
                ('rentzestimate_last_updated', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZillowDetails',
            fields=[
                ('zillow_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('zestimate_amount', models.IntegerField(null=True)),
                ('zestimate_last_updated', models.DateField(null=True)),
                ('zillow_id', models.IntegerField(null=True)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PropertyAddress'),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.RentalDetails'),
        ),
        migrations.AddField(
            model_name='property',
            name='zillow_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ZillowDetails'),
        ),
    ]
